/-
  AUTO-GENERATED by `verifier emit`. Do not edit by hand.
-/

import CodeLib.GeneratedCore

set_option maxRecDepth 1048576

namespace Project.F64Dot

open Wasm

def func0 : Wasm.Program := watFunctionBody% "../rust/build/f64_dot/program.wat" 0

def func0Def : Wasm.Function :=
  { params := [.i32, .i32, .i32], locals := [.f64], body := func0, results := [.f64], typeIdx := some 0 }

def «module» : Wasm.Module :=
  { (watModuleMetadata% "../rust/build/f64_dot/program.wat") with funcs := [func0Def] }

-- Compile-time fidelity check: errors if WAT and generated Lean AST differ.
#guard_msgs (drop info) in
#eval Wasm.checkWatFidelity "../rust/build/f64_dot/program.wat" «module»

end Project.F64Dot
