import Interpreter.Wasm.Float

/-!
# Pure binary32 regression checks

These checks compare the proof-visible binary32 addition and subtraction
against the platform `Float32` implementation.  They are testing evidence,
not logical bridge axioms: numerical proofs use only the pure definitions.
-/

namespace Wasm.Examples.IEEE32

private def nativeAdd (a b : UInt32) : UInt32 :=
  f32Canon (Float32.ofBits a + Float32.ofBits b).toBits

private def nativeSub (a b : UInt32) : UInt32 :=
  f32Canon (Float32.ofBits a - Float32.ofBits b).toBits

/-- Cases selected to exercise signs, zero, subnormals, the normal boundary,
ties-to-even, cancellation, overflow, infinities, and NaNs. -/
def edgeCases : List (UInt32 × UInt32) :=
  [ (0x00000000, 0x80000000)
  , (0x80000000, 0x80000000)
  , (0x3F800000, 0xBF800000)
  , (0x00000001, 0x00000001)
  , (0x007FFFFF, 0x00000001)
  , (0x00800000, 0x80000001)
  , (0x3F800000, 0x33800000)
  , (0x3F800000, 0x34400000)
  , (0x7F7FFFFF, 0x7F7FFFFF)
  , (0x7F7FFFFF, 0xFF7FFFFF)
  , (0x7F800000, 0x3F800000)
  , (0xFF800000, 0xBF800000)
  , (0x7F800000, 0xFF800000)
  , (0x7FC00000, 0x3F800000)
  , (0x7FA00001, 0xFF800000)
  , (0x00000001, 0x80000001)
  , (0x3F000000, 0x33000000)
  , (0x4B000000, 0x3F800000)
  , (0x00800000, 0x80800000)
  , (0x7F000000, 0x3F800000) ]

theorem edge_add_agrees_with_native :
    edgeCases.all (fun p => IEEE32.add p.1 p.2 == nativeAdd p.1 p.2) = true := by
  native_decide

theorem edge_sub_agrees_with_native :
    edgeCases.all (fun p => IEEE32.sub p.1 p.2 == nativeSub p.1 p.2) = true := by
  native_decide

/-- Deterministic full-width inputs generated by two independent linear
congruential sequences. -/
def differentialCases : List (UInt32 × UInt32) :=
  (List.range 4096).map fun n =>
    ( UInt32.ofNat (1664525 * n + 1013904223)
    , UInt32.ofNat (22695477 * n + 1) )

theorem differential_add_agrees_with_native :
    differentialCases.all
      (fun p => IEEE32.add p.1 p.2 == nativeAdd p.1 p.2) = true := by
  native_decide

theorem differential_sub_agrees_with_native :
    differentialCases.all
      (fun p => IEEE32.sub p.1 p.2 == nativeSub p.1 p.2) = true := by
  native_decide

theorem differential_negate_agrees_with_bit_flip :
    differentialCases.all
      (fun p => IEEE32.negate p.1 == (p.1 ^^^ 0x80000000)) = true := by
  native_decide

theorem differential_abs_agrees_with_sign_clear :
    differentialCases.all
      (fun p => IEEE32.abs p.1 == (p.1 &&& 0x7FFFFFFF)) = true := by
  native_decide

/-- The exact halfway increment above the largest finite positive value rounds
to positive infinity; ties go to the even conceptual significand. -/
theorem positive_overflow_tie_agrees_with_native :
    IEEE32.add 0x7F7FFFFF 0x73000000 = 0x7F800000 ∧
      nativeAdd 0x7F7FFFFF 0x73000000 = 0x7F800000 := by
  native_decide

/-- A quarter-ULP increment remains below the overflow midpoint and rounds
back to the largest finite value. -/
theorem below_positive_overflow_tie_agrees_with_native :
    IEEE32.add 0x7F7FFFFF 0x72800000 = 0x7F7FFFFF ∧
      nativeAdd 0x7F7FFFFF 0x72800000 = 0x7F7FFFFF := by
  native_decide

theorem negative_overflow_tie_agrees_with_native :
    IEEE32.add 0xFF7FFFFF 0xF3000000 = 0xFF800000 ∧
      nativeAdd 0xFF7FFFFF 0xF3000000 = 0xFF800000 := by
  native_decide

theorem subtraction_overflow_tie_agrees_with_native :
    IEEE32.sub 0x7F7FFFFF 0xF3000000 = 0x7F800000 ∧
      nativeSub 0x7F7FFFFF 0xF3000000 = 0x7F800000 := by
  native_decide

end Wasm.Examples.IEEE32
