import Interpreter.Wasm.Float

/-!
# Pure binary32 regression checks

These checks compare the proof-visible binary32 addition and subtraction
against the platform `Float32` implementation.  They are testing evidence,
not logical bridge axioms: numerical proofs use only the pure definitions.
-/

namespace Wasm.Examples.IEEE32

private def nativeAdd (a b : UInt32) : UInt32 :=
  f32Canon (Float32.ofBits a + Float32.ofBits b).toBits

private def nativeSub (a b : UInt32) : UInt32 :=
  f32Canon (Float32.ofBits a - Float32.ofBits b).toBits

/-- Cases selected to exercise signs, zero, subnormals, the normal boundary,
ties-to-even, cancellation, overflow, infinities, and NaNs. -/
def edgeCases : List (UInt32 × UInt32) :=
  [ (0x00000000, 0x80000000)
  , (0x80000000, 0x80000000)
  , (0x3F800000, 0xBF800000)
  , (0x00000001, 0x00000001)
  , (0x007FFFFF, 0x00000001)
  , (0x00800000, 0x80000001)
  , (0x3F800000, 0x33800000)
  , (0x3F800000, 0x34400000)
  , (0x7F7FFFFF, 0x7F7FFFFF)
  , (0x7F7FFFFF, 0xFF7FFFFF)
  , (0x7F800000, 0x3F800000)
  , (0xFF800000, 0xBF800000)
  , (0x7F800000, 0xFF800000)
  , (0x7FC00000, 0x3F800000)
  , (0x7FA00001, 0xFF800000)
  , (0x00000001, 0x80000001)
  , (0x3F000000, 0x33000000)
  , (0x4B000000, 0x3F800000)
  , (0x00800000, 0x80800000)
  , (0x7F000000, 0x3F800000) ]

theorem edge_add_agrees_with_native :
    edgeCases.all (fun p => IEEE32.add p.1 p.2 == nativeAdd p.1 p.2) = true := by
  native_decide

theorem edge_sub_agrees_with_native :
    edgeCases.all (fun p => IEEE32.sub p.1 p.2 == nativeSub p.1 p.2) = true := by
  native_decide

/-- Deterministic full-width inputs generated by two independent linear
congruential sequences. -/
def differentialCases : List (UInt32 × UInt32) :=
  (List.range 4096).map fun n =>
    ( UInt32.ofNat (1664525 * n + 1013904223)
    , UInt32.ofNat (22695477 * n + 1) )

theorem differential_add_agrees_with_native :
    differentialCases.all
      (fun p => IEEE32.add p.1 p.2 == nativeAdd p.1 p.2) = true := by
  native_decide

theorem differential_sub_agrees_with_native :
    differentialCases.all
      (fun p => IEEE32.sub p.1 p.2 == nativeSub p.1 p.2) = true := by
  native_decide

end Wasm.Examples.IEEE32
