import Interpreter.Wasm.Float

/-!
# Pure binary32 regression checks

These checks compare the proof-visible binary32 addition, subtraction, and multiplication
against the platform `Float32` implementation.  They are testing evidence,
not logical bridge axioms: numerical proofs use only the pure definitions.
-/

namespace Wasm.Examples.IEEE32

private def nativeAdd (a b : UInt32) : UInt32 :=
  f32Canon (Float32.ofBits a + Float32.ofBits b).toBits

private def nativeSub (a b : UInt32) : UInt32 :=
  f32Canon (Float32.ofBits a - Float32.ofBits b).toBits

private def nativeMul (a b : UInt32) : UInt32 :=
  f32Canon (Float32.ofBits a * Float32.ofBits b).toBits

private def nativeDiv (a b : UInt32) : UInt32 :=
  f32Canon (Float32.ofBits a / Float32.ofBits b).toBits

private def nativeSqrt (a : UInt32) : UInt32 :=
  f32Canon (Float32.ofBits a).sqrt.toBits

private def nativeMin (a b : UInt32) : UInt32 :=
  let x := Float32.ofBits a
  let y := Float32.ofBits b
  if x.isNaN || y.isNaN then f32CanonicalNaN
  else if x.toFloat == 0.0 && y.toFloat == 0.0 then a ||| b
  else if x.toFloat < y.toFloat then a else b

private def nativeMax (a b : UInt32) : UInt32 :=
  let x := Float32.ofBits a
  let y := Float32.ofBits b
  if x.isNaN || y.isNaN then f32CanonicalNaN
  else if x.toFloat == 0.0 && y.toFloat == 0.0 then a &&& b
  else if x.toFloat < y.toFloat then b else a

private def nativeEq (a b : UInt32) : Bool :=
  (Float32.ofBits a).toFloat == (Float32.ofBits b).toFloat

private def nativeLt (a b : UInt32) : Bool :=
  decide ((Float32.ofBits a).toFloat < (Float32.ofBits b).toFloat)

private def nativeLe (a b : UInt32) : Bool :=
  decide ((Float32.ofBits a).toFloat ≤ (Float32.ofBits b).toFloat)

private def nativeCeil (a : UInt32) : UInt32 :=
  f32Canon (Float32.ofBits a).ceil.toBits

private def nativeFloor (a : UInt32) : UInt32 :=
  f32Canon (Float32.ofBits a).floor.toBits

private def nativeTrunc (a : UInt32) : UInt32 :=
  let x := Float32.ofBits a
  f32Canon (if x.toFloat < 0.0 then x.ceil else x.floor).toBits

private def nativeNearest (a : UInt32) : UInt32 :=
  let x := Float32.ofBits a
  let fl := x.floor
  let cl := x.ceil
  let dlo := x.toFloat - fl.toFloat
  let dhi := cl.toFloat - x.toFloat
  let r := if dlo < dhi then fl
    else if dhi < dlo then cl
    else if (fl.toFloat * 0.5).floor * 2.0 == fl.toFloat then fl else cl
  f32Canon r.toBits

/-- Cases selected to exercise signs, zero, subnormals, the normal boundary,
ties-to-even, cancellation, overflow, infinities, and NaNs. -/
def edgeCases : List (UInt32 × UInt32) :=
  [ (0x00000000, 0x80000000)
  , (0x80000000, 0x80000000)
  , (0x3F800000, 0xBF800000)
  , (0x00000001, 0x00000001)
  , (0x007FFFFF, 0x00000001)
  , (0x00800000, 0x80000001)
  , (0x3F800000, 0x33800000)
  , (0x3F800000, 0x34400000)
  , (0x7F7FFFFF, 0x7F7FFFFF)
  , (0x7F7FFFFF, 0xFF7FFFFF)
  , (0x7F800000, 0x3F800000)
  , (0xFF800000, 0xBF800000)
  , (0x7F800000, 0xFF800000)
  , (0x7FC00000, 0x3F800000)
  , (0x7FA00001, 0xFF800000)
  , (0x00000001, 0x80000001)
  , (0x3F000000, 0x33000000)
  , (0x4B000000, 0x3F800000)
  , (0x00800000, 0x80800000)
  , (0x7F000000, 0x3F800000) ]

theorem edge_add_agrees_with_native :
    edgeCases.all (fun p => IEEE32.add p.1 p.2 == nativeAdd p.1 p.2) = true := by
  native_decide

theorem edge_sub_agrees_with_native :
    edgeCases.all (fun p => IEEE32.sub p.1 p.2 == nativeSub p.1 p.2) = true := by
  native_decide

theorem edge_mul_agrees_with_native :
    edgeCases.all (fun p => IEEE32.mul p.1 p.2 == nativeMul p.1 p.2) = true := by
  native_decide

theorem edge_div_agrees_with_native :
    edgeCases.all (fun p => IEEE32.div p.1 p.2 == nativeDiv p.1 p.2) = true := by
  native_decide

/-- Deterministic full-width inputs generated by two independent linear
congruential sequences. -/
def differentialCases : List (UInt32 × UInt32) :=
  (List.range 4096).map fun n =>
    ( UInt32.ofNat (1664525 * n + 1013904223)
    , UInt32.ofNat (22695477 * n + 1) )

theorem differential_add_agrees_with_native :
    differentialCases.all
      (fun p => IEEE32.add p.1 p.2 == nativeAdd p.1 p.2) = true := by
  native_decide

theorem differential_sub_agrees_with_native :
    differentialCases.all
      (fun p => IEEE32.sub p.1 p.2 == nativeSub p.1 p.2) = true := by
  native_decide

theorem differential_mul_agrees_with_native :
    differentialCases.all
      (fun p => IEEE32.mul p.1 p.2 == nativeMul p.1 p.2) = true := by
  native_decide

theorem differential_div_agrees_with_native :
    differentialCases.all
      (fun p => IEEE32.div p.1 p.2 == nativeDiv p.1 p.2) = true := by
  native_decide

theorem differential_sqrt_agrees_with_native :
    differentialCases.all
      (fun p => IEEE32.sqrt p.1 == nativeSqrt p.1) = true := by
  native_decide

theorem differential_selection_and_comparison_agree_with_native :
    differentialCases.all (fun p =>
      IEEE32.min p.1 p.2 == nativeMin p.1 p.2 &&
      IEEE32.max p.1 p.2 == nativeMax p.1 p.2 &&
      IEEE32.eq p.1 p.2 == nativeEq p.1 p.2 &&
      IEEE32.lt p.1 p.2 == nativeLt p.1 p.2 &&
      IEEE32.le p.1 p.2 == nativeLe p.1 p.2) = true := by
  native_decide

theorem edge_selection_and_comparison_agree_with_native :
    edgeCases.all (fun p =>
      IEEE32.min p.1 p.2 == nativeMin p.1 p.2 &&
      IEEE32.max p.1 p.2 == nativeMax p.1 p.2 &&
      IEEE32.eq p.1 p.2 == nativeEq p.1 p.2 &&
      IEEE32.lt p.1 p.2 == nativeLt p.1 p.2 &&
      IEEE32.le p.1 p.2 == nativeLe p.1 p.2) = true := by
  native_decide

theorem differential_copySign_agrees_with_bit_operation :
    differentialCases.all (fun p =>
      IEEE32.copySign p.1 p.2 ==
        ((p.1 &&& 0x7FFFFFFF) ||| (p.2 &&& 0x80000000))) = true := by
  native_decide

theorem differential_integral_rounding_agrees_with_native :
    differentialCases.all (fun p =>
      IEEE32.ceil p.1 == nativeCeil p.1 &&
      IEEE32.floor p.1 == nativeFloor p.1 &&
      IEEE32.trunc p.1 == nativeTrunc p.1 &&
      IEEE32.nearest p.1 == nativeNearest p.1) = true := by
  native_decide

/-- Multiplication crosses the normal/subnormal boundary exactly. -/
theorem multiplication_min_normal_by_half_agrees_with_native :
    IEEE32.mul 0x00800000 0x3F000000 = 0x00400000 ∧
      nativeMul 0x00800000 0x3F000000 = 0x00400000 := by
  native_decide

/-- Half of the least subnormal is a tie between zero and the least
subnormal; ties-to-even selects signed zero. -/
theorem multiplication_underflow_tie_agrees_with_native :
    IEEE32.mul 0x00000001 0x3F000000 = 0x00000000 ∧
      IEEE32.mul 0x80000001 0x3F000000 = 0x80000000 ∧
      nativeMul 0x00000001 0x3F000000 = 0x00000000 ∧
      nativeMul 0x80000001 0x3F000000 = 0x80000000 := by
  native_decide

/-- Zero times infinity is invalid and canonicalizes to NaN. -/
theorem multiplication_zero_infinity_agrees_with_native :
    IEEE32.mul 0x00000000 0x7F800000 = IEEE32.canonicalNaN ∧
      nativeMul 0x00000000 0x7F800000 = IEEE32.canonicalNaN := by
  native_decide

theorem division_exact_agrees_with_native :
    IEEE32.div 0x40C00000 0x40800000 = 0x3FC00000 ∧
      nativeDiv 0x40C00000 0x40800000 = 0x3FC00000 := by
  native_decide

theorem division_gradual_underflow_agrees_with_native :
    IEEE32.div 0x00800000 0x40000000 = 0x00400000 ∧
      nativeDiv 0x00800000 0x40000000 = 0x00400000 := by
  native_decide

theorem division_by_zero_agrees_with_native :
    IEEE32.div 0x3F800000 0x00000000 = 0x7F800000 ∧
      IEEE32.div 0x00000000 0x00000000 = IEEE32.canonicalNaN ∧
      nativeDiv 0x3F800000 0x00000000 = 0x7F800000 ∧
      nativeDiv 0x00000000 0x00000000 = IEEE32.canonicalNaN := by
  native_decide

theorem square_root_special_cases_agree_with_native :
    IEEE32.sqrt 0x00000000 = 0x00000000 ∧
      IEEE32.sqrt 0x80000000 = 0x80000000 ∧
      IEEE32.sqrt 0x7F800000 = 0x7F800000 ∧
      IEEE32.sqrt 0xBF800000 = IEEE32.canonicalNaN ∧
      nativeSqrt 0x00000000 = 0x00000000 ∧
      nativeSqrt 0x80000000 = 0x80000000 ∧
      nativeSqrt 0x7F800000 = 0x7F800000 ∧
      nativeSqrt 0xBF800000 = IEEE32.canonicalNaN := by
  native_decide

theorem square_root_exact_and_rounded_agree_with_native :
    IEEE32.sqrt 0x40800000 = 0x40000000 ∧
      IEEE32.sqrt 0x40000000 = nativeSqrt 0x40000000 ∧
      IEEE32.sqrt 0x00000001 = nativeSqrt 0x00000001 := by
  native_decide

theorem differential_negate_agrees_with_bit_flip :
    differentialCases.all
      (fun p => IEEE32.negate p.1 == (p.1 ^^^ 0x80000000)) = true := by
  native_decide

theorem differential_abs_agrees_with_sign_clear :
    differentialCases.all
      (fun p => IEEE32.abs p.1 == (p.1 &&& 0x7FFFFFFF)) = true := by
  native_decide

/-- The exact halfway increment above the largest finite positive value rounds
to positive infinity; ties go to the even conceptual significand. -/
theorem positive_overflow_tie_agrees_with_native :
    IEEE32.add 0x7F7FFFFF 0x73000000 = 0x7F800000 ∧
      nativeAdd 0x7F7FFFFF 0x73000000 = 0x7F800000 := by
  native_decide

/-- A quarter-ULP increment remains below the overflow midpoint and rounds
back to the largest finite value. -/
theorem below_positive_overflow_tie_agrees_with_native :
    IEEE32.add 0x7F7FFFFF 0x72800000 = 0x7F7FFFFF ∧
      nativeAdd 0x7F7FFFFF 0x72800000 = 0x7F7FFFFF := by
  native_decide

theorem negative_overflow_tie_agrees_with_native :
    IEEE32.add 0xFF7FFFFF 0xF3000000 = 0xFF800000 ∧
      nativeAdd 0xFF7FFFFF 0xF3000000 = 0xFF800000 := by
  native_decide

theorem subtraction_overflow_tie_agrees_with_native :
    IEEE32.sub 0x7F7FFFFF 0xF3000000 = 0x7F800000 ∧
      nativeSub 0x7F7FFFFF 0xF3000000 = 0x7F800000 := by
  native_decide

end Wasm.Examples.IEEE32