name = "Interpreter"
version = "0.1.0"
defaultTargets = ["Interpreter"]
packagesDir = "../.lake/packages"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.34.0-rc2"

[[lean_lib]]
name = "Interpreter"

[[lean_exe]]
name = "runner"
root = "Interpreter.Runner"

[[lean_exe]]
name = "testsuite"
root = "Interpreter.Testsuite"
